language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-google-m2repository
    - extra-google-m2repository__y
    - sys-img-armeabi-v7a-android-22

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-22
    - android-28
    - android-29

#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
#    - $HOME/.android/build-cache

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

#before_install:
#  # Install SDK license so Android Gradle plugin can install deps.
#  - mkdir "$ANDROID_HOME/licenses" || true
#  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
#  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew test

#after_success:
#  - . ./ci/deploy.sh